// AUTO-GENERATED by the localization pipeline. Do not edit by hand.
import { starter as jaJP_starter } from "./ja-JP";
import { starter as koKR_starter } from "./ko-KR";
import { starter as zhTW_starter } from "./zh-TW";
import { starter as frFR_starter } from "./fr-FR";
import { starter as deDE_starter } from "./de-DE";
import { starter as esES_starter } from "./es-ES";
import { starter as ptBR_starter } from "./pt-BR";
import { starter as ruRU_starter } from "./ru-RU";
import { starter as itIT_starter } from "./it-IT";
import { starter as nlNL_starter } from "./nl-NL";
import { starter as trTR_starter } from "./tr-TR";
import { starter as plPL_starter } from "./pl-PL";
import { starter as viVN_starter } from "./vi-VN";
import { starter as thTH_starter } from "./th-TH";
import { starter as idID_starter } from "./id-ID";
import { starter as arEG_starter } from "./ar-EG";
import { starter as csCZ_starter } from "./cs-CZ";
import { starter as heIL_starter } from "./he-IL";
import { starter as hiIN_starter } from "./hi-IN";
import { starter as svSE_starter } from "./sv-SE";
import { starter as ukUA_starter } from "./uk-UA";
import { inv as jaJP_inv } from "./inv/ja-JP";
import { inv as koKR_inv } from "./inv/ko-KR";
import { inv as zhTW_inv } from "./inv/zh-TW";
import { inv as frFR_inv } from "./inv/fr-FR";
import { inv as deDE_inv } from "./inv/de-DE";
import { inv as esES_inv } from "./inv/es-ES";
import { inv as ptBR_inv } from "./inv/pt-BR";
import { inv as ruRU_inv } from "./inv/ru-RU";
import { inv as itIT_inv } from "./inv/it-IT";
import { inv as nlNL_inv } from "./inv/nl-NL";
import { inv as trTR_inv } from "./inv/tr-TR";
import { inv as plPL_inv } from "./inv/pl-PL";
import { inv as viVN_inv } from "./inv/vi-VN";
import { inv as thTH_inv } from "./inv/th-TH";
import { inv as idID_inv } from "./inv/id-ID";
import { inv as arEG_inv } from "./inv/ar-EG";
import { inv as csCZ_inv } from "./inv/cs-CZ";
import { inv as heIL_inv } from "./inv/he-IL";
import { inv as hiIN_inv } from "./inv/hi-IN";
import { inv as svSE_inv } from "./inv/sv-SE";
import { inv as ukUA_inv } from "./inv/uk-UA";

export const additionalTranslations: Record<string, Record<string, Record<string, string>>> = {
  "starter": {
    "ja-JP": jaJP_starter,
    "ko-KR": koKR_starter,
    "zh-TW": zhTW_starter,
    "fr-FR": frFR_starter,
    "de-DE": deDE_starter,
    "es-ES": esES_starter,
    "pt-BR": ptBR_starter,
    "ru-RU": ruRU_starter,
    "it-IT": itIT_starter,
    "nl-NL": nlNL_starter,
    "tr-TR": trTR_starter,
    "pl-PL": plPL_starter,
    "vi-VN": viVN_starter,
    "th-TH": thTH_starter,
    "id-ID": idID_starter,
    "ar-EG": arEG_starter,
    "cs-CZ": csCZ_starter,
    "he-IL": heIL_starter,
    "hi-IN": hiIN_starter,
    "sv-SE": svSE_starter,
    "uk-UA": ukUA_starter,
  },
  "inv": {
    "ja-JP": jaJP_inv,
    "ko-KR": koKR_inv,
    "zh-TW": zhTW_inv,
    "fr-FR": frFR_inv,
    "de-DE": deDE_inv,
    "es-ES": esES_inv,
    "pt-BR": ptBR_inv,
    "ru-RU": ruRU_inv,
    "it-IT": itIT_inv,
    "nl-NL": nlNL_inv,
    "tr-TR": trTR_inv,
    "pl-PL": plPL_inv,
    "vi-VN": viVN_inv,
    "th-TH": thTH_inv,
    "id-ID": idID_inv,
    "ar-EG": arEG_inv,
    "cs-CZ": csCZ_inv,
    "he-IL": heIL_inv,
    "hi-IN": hiIN_inv,
    "sv-SE": svSE_inv,
    "uk-UA": ukUA_inv,
  },
};
