// AUTO-GENERATED by the localization pipeline. Do not edit by hand.
import { usersExample as jaJP_usersExample } from "./ja-JP";
import { usersExample as koKR_usersExample } from "./ko-KR";
import { usersExample as zhTW_usersExample } from "./zh-TW";
import { usersExample as frFR_usersExample } from "./fr-FR";
import { usersExample as deDE_usersExample } from "./de-DE";
import { usersExample as esES_usersExample } from "./es-ES";
import { usersExample as ptBR_usersExample } from "./pt-BR";
import { usersExample as ruRU_usersExample } from "./ru-RU";
import { usersExample as itIT_usersExample } from "./it-IT";
import { usersExample as nlNL_usersExample } from "./nl-NL";
import { usersExample as trTR_usersExample } from "./tr-TR";
import { usersExample as plPL_usersExample } from "./pl-PL";
import { usersExample as viVN_usersExample } from "./vi-VN";
import { usersExample as thTH_usersExample } from "./th-TH";
import { usersExample as idID_usersExample } from "./id-ID";
import { usersExample as arEG_usersExample } from "./ar-EG";
import { usersExample as csCZ_usersExample } from "./cs-CZ";
import { usersExample as heIL_usersExample } from "./he-IL";
import { usersExample as hiIN_usersExample } from "./hi-IN";
import { usersExample as svSE_usersExample } from "./sv-SE";
import { usersExample as ukUA_usersExample } from "./uk-UA";

export const additionalTranslations: Record<string, Record<string, string>> = {
  "ja-JP": jaJP_usersExample,
  "ko-KR": koKR_usersExample,
  "zh-TW": zhTW_usersExample,
  "fr-FR": frFR_usersExample,
  "de-DE": deDE_usersExample,
  "es-ES": esES_usersExample,
  "pt-BR": ptBR_usersExample,
  "ru-RU": ruRU_usersExample,
  "it-IT": itIT_usersExample,
  "nl-NL": nlNL_usersExample,
  "tr-TR": trTR_usersExample,
  "pl-PL": plPL_usersExample,
  "vi-VN": viVN_usersExample,
  "th-TH": thTH_usersExample,
  "id-ID": idID_usersExample,
  "ar-EG": arEG_usersExample,
  "cs-CZ": csCZ_usersExample,
  "he-IL": heIL_usersExample,
  "hi-IN": hiIN_usersExample,
  "sv-SE": svSE_usersExample,
  "uk-UA": ukUA_usersExample,
};
